### ISSUE TITLE
Error when gem is not installed locally

### ISSUE THREAD

**Issue by dankohn** [DruRly/gemrat#21]
Whenever I install a new gem, I get an error if it's not already on the machine. It still adds the gem to my Gemfile, so I still use gemrat and then enter `bundle`.

```
$ gemrat railroady
gem 'railroady', '1.1.2' added to your Gemfile.
Bundling...
/Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/resolver.rb:357:in `resolve': Could not find gem 'railroady (= 1.1.2) ruby' in the gems available on this machine. (Bundler::GemNotFound)
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/resolver.rb:164:in `start'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/resolver.rb:129:in `resolve'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/definition.rb:202:in `resolve'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/definition.rb:132:in `specs'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/definition.rb:177:in `specs_for'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/definition.rb:166:in `requested_specs'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/environment.rb:18:in `requested_specs'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/runtime.rb:13:in `setup'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler.rb:121:in `setup'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.0/lib/bundler/setup.rb:17:in `<top (required)>'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by shime** [comment]
This seems like a bundler issue. What happens if you add the gem manually to the Gemfile?

**Comment by surfer190** [comment]
Add to your `Gemfile`:

```
source 'https://rubygems.org'
```
