### ISSUE TITLE
`gemrat pry` is malformed in the gemfile

### ISSUE THREAD

**Issue by samjewell** [DruRly/gemrat#24]
I'm hitting this error message when I try to `gemrat pry`
```
There was an error parsing `Gemfile`: Illformed requirement ["0.10.4 ruby java"]. Bundler cannot continue.
```

### Full trace:
```
➜  gemrat-bug gemrat pry
gem 'pry', '0.10.4 ruby java' added to your Gemfile.
Bundling...
/Users/samjewell/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/requirement.rb:101:in `parse':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: Illformed requirement ["0.10.4 ruby java"]. Bundler cannot continue.

 #  from /Users/samjewell/bu/s3migrate/gemrat-bug/Gemfile:56
 #  -------------------------------------------
 #  gem 'gemrat', '0.4.6'
 >  gem 'pry', '0.10.4 ruby java'
 #  -------------------------------------------
	from /Users/samjewell/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `block in initialize'
	from /Users/samjewell/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `map!'
	from /Users/samjewell/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/requirement.rb:131:in `initialize'
	from /Users/samjewell/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/requirement.rb:59:in `new'
	from /Users/samjewell/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/requirement.rb:59:in `create'
	from /Users/samjewell/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:59:in `initialize'
	from /Users/samjewell/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/dependency.rb:75:in `initialize'
	from /Users/samjewell/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/dsl.rb:94:in `new'
	from /Users/samjewell/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/dsl.rb:94:in `gem'
	from /Users/samjewell/bu/s3migrate/gemrat-bug/Gemfile:56:in `eval_gemfile'
	from /Users/samjewell/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/dsl.rb:41:in `instance_eval'
	from /Users/samjewell/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/dsl.rb:41:in `eval_gemfile'
	from /Users/samjewell/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/dsl.rb:11:in `evaluate'
	from /Users/samjewell/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/definition.rb:33:in `build'
	from /Users/samjewell/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler.rb:127:in `definition'
	from /Users/samjewell/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler.rb:93:in `setup'
	from /Users/samjewell/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/setup.rb:20:in `<top (required)>'
	from /Users/samjewell/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/samjewell/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

### Reproduction steps:
```
 4010  rails new gemrat-bug
 4012  cd gemrat-bug
 4014  gem install gemrat
 4015  gemrat gemrat
 4018  bundle
 4019  gemrat pry
```

**Comment by thisredone** [comment]
Same thing with `pg`

    [!] There was an error parsing `Gemfile`: Illformed requirement ["0.21.0 ruby x64-mingw32 x86-mingw32"]. Bundler cannot continue.

     #  from Gemfile:12
     #  -------------------------------------------
     #  
     >  gem 'pg', '0.21.0 ruby x64-mingw32 x86-mingw32'
     #  -------------------------------------------
